// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package types

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AttachmentTargetType.
const (
	AttachmentTargetTypeGroup AttachmentTargetType = "group"
	AttachmentTargetTypeUser  AttachmentTargetType = "user"
)

// Valid indicates whether the value is a known member of the AttachmentTargetType enum.
func (e AttachmentTargetType) Valid() bool {
	switch e {
	case AttachmentTargetTypeGroup:
		return true
	case AttachmentTargetTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for CheckAuthorizationResponseDecision.
const (
	ALLOW CheckAuthorizationResponseDecision = "ALLOW"
	DENY  CheckAuthorizationResponseDecision = "DENY"
)

// Valid indicates whether the value is a known member of the CheckAuthorizationResponseDecision enum.
func (e CheckAuthorizationResponseDecision) Valid() bool {
	switch e {
	case ALLOW:
		return true
	case DENY:
		return true
	default:
		return false
	}
}

// Defines values for ClusterStatusInfoPhase.
const (
	ClusterStatusInfoPhaseFailed      ClusterStatusInfoPhase = "Failed"
	ClusterStatusInfoPhasePending     ClusterStatusInfoPhase = "Pending"
	ClusterStatusInfoPhaseProgressing ClusterStatusInfoPhase = "Progressing"
	ClusterStatusInfoPhaseReady       ClusterStatusInfoPhase = "Ready"
)

// Valid indicates whether the value is a known member of the ClusterStatusInfoPhase enum.
func (e ClusterStatusInfoPhase) Valid() bool {
	switch e {
	case ClusterStatusInfoPhaseFailed:
		return true
	case ClusterStatusInfoPhasePending:
		return true
	case ClusterStatusInfoPhaseProgressing:
		return true
	case ClusterStatusInfoPhaseReady:
		return true
	default:
		return false
	}
}

// Defines values for ConditionStatus.
const (
	False   ConditionStatus = "false"
	True    ConditionStatus = "true"
	Unknown ConditionStatus = "Unknown"
)

// Valid indicates whether the value is a known member of the ConditionStatus enum.
func (e ConditionStatus) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for CreateAttachmentRequestTargetType.
const (
	CreateAttachmentRequestTargetTypeGroup CreateAttachmentRequestTargetType = "group"
	CreateAttachmentRequestTargetTypeUser  CreateAttachmentRequestTargetType = "user"
)

// Valid indicates whether the value is a known member of the CreateAttachmentRequestTargetType enum.
func (e CreateAttachmentRequestTargetType) Valid() bool {
	switch e {
	case CreateAttachmentRequestTargetTypeGroup:
		return true
	case CreateAttachmentRequestTargetTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	Degraded    HealthStatusStatus = "degraded"
	Ok          HealthStatusStatus = "ok"
	Unavailable HealthStatusStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for NodePoolStatusInfoPhase.
const (
	NodePoolStatusInfoPhaseFailed      NodePoolStatusInfoPhase = "Failed"
	NodePoolStatusInfoPhasePending     NodePoolStatusInfoPhase = "Pending"
	NodePoolStatusInfoPhaseProgressing NodePoolStatusInfoPhase = "Progressing"
	NodePoolStatusInfoPhaseReady       NodePoolStatusInfoPhase = "Ready"
)

// Valid indicates whether the value is a known member of the NodePoolStatusInfoPhase enum.
func (e NodePoolStatusInfoPhase) Valid() bool {
	switch e {
	case NodePoolStatusInfoPhaseFailed:
		return true
	case NodePoolStatusInfoPhasePending:
		return true
	case NodePoolStatusInfoPhaseProgressing:
		return true
	case NodePoolStatusInfoPhaseReady:
		return true
	default:
		return false
	}
}

// Defines values for PolicyStatementEffect.
const (
	Allow PolicyStatementEffect = "Allow"
	Deny  PolicyStatementEffect = "Deny"
)

// Valid indicates whether the value is a known member of the PolicyStatementEffect enum.
func (e PolicyStatementEffect) Valid() bool {
	switch e {
	case Allow:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// Defines values for V0PolicyVersion.
const (
	V0 V0PolicyVersion = "v0"
)

// Valid indicates whether the value is a known member of the V0PolicyVersion enum.
func (e V0PolicyVersion) Valid() bool {
	switch e {
	case V0:
		return true
	default:
		return false
	}
}

// Defines values for ListAttachmentsParamsTargetType.
const (
	ListAttachmentsParamsTargetTypeGroup ListAttachmentsParamsTargetType = "group"
	ListAttachmentsParamsTargetTypeUser  ListAttachmentsParamsTargetType = "user"
)

// Valid indicates whether the value is a known member of the ListAttachmentsParamsTargetType enum.
func (e ListAttachmentsParamsTargetType) Valid() bool {
	switch e {
	case ListAttachmentsParamsTargetTypeGroup:
		return true
	case ListAttachmentsParamsTargetTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for ListUserClustersParamsStatus.
const (
	Failed      ListUserClustersParamsStatus = "Failed"
	Pending     ListUserClustersParamsStatus = "Pending"
	Progressing ListUserClustersParamsStatus = "Progressing"
	Ready       ListUserClustersParamsStatus = "Ready"
)

// Valid indicates whether the value is a known member of the ListUserClustersParamsStatus enum.
func (e ListUserClustersParamsStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Progressing:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Account An enabled account
type Account struct {
	// AccountId AWS account ID
	AccountId string `json:"accountId"`

	// CreatedAt When the account was enabled
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy ARN of who enabled the account
	CreatedBy *string `json:"createdBy,omitempty"`

	// PolicyStoreId AVP policy store ID (null if privileged)
	PolicyStoreId *string `json:"policyStoreId,omitempty"`

	// Privileged If true, bypasses all authorization
	Privileged bool `json:"privileged"`
}

// AccountList List of accounts
type AccountList struct {
	Items []Account `json:"items"`
	Kind  string    `json:"kind"`

	// Total Total number of accounts
	Total int `json:"total"`
}

// AddAdminRequest Request body for adding an admin
type AddAdminRequest struct {
	// PrincipalArn ARN of the principal to make admin
	PrincipalArn string `json:"principalArn"`
}

// Admin An admin for the account
type Admin struct {
	// CreatedAt When the admin was added
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy ARN of who added this admin
	CreatedBy *string `json:"createdBy,omitempty"`

	// PrincipalArn Admin's AWS ARN
	PrincipalArn string `json:"principalArn"`
}

// AdminList Paginated list of admins
type AdminList struct {
	Items []Admin `json:"items"`
	Kind  string  `json:"kind"`
	Page  int     `json:"page"`
	Size  int     `json:"size"`
	Total int     `json:"total"`
}

// Attachment A policy attachment to a user or group
type Attachment struct {
	// AvpPolicyId Policy ID in Amazon Verified Permissions
	AvpPolicyId *string `json:"avpPolicyId,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Href API href reference
	Href string `json:"href"`

	// Id Attachment ID
	Id   openapi_types.UUID `json:"id"`
	Kind string             `json:"kind"`

	// PolicyId Attached policy ID
	PolicyId openapi_types.UUID `json:"policyId"`

	// PolicyName Attached policy name
	PolicyName *string `json:"policyName,omitempty"`

	// TargetId Target ID
	TargetId string `json:"targetId"`

	// TargetType Target type
	TargetType AttachmentTargetType `json:"targetType"`
}

// AttachmentTargetType Target type
type AttachmentTargetType string

// AttachmentList Paginated list of attachments
type AttachmentList struct {
	Items []Attachment `json:"items"`
	Kind  string       `json:"kind"`
	Page  int          `json:"page"`
	Size  int          `json:"size"`
	Total int          `json:"total"`
}

// CheckAuthorizationRequest Request body for checking authorization
type CheckAuthorizationRequest struct {
	// Action Action being performed (e.g., rosa:CreateCluster)
	Action string `json:"action"`

	// Context Additional context for the authorization decision
	Context *map[string]interface{} `json:"context,omitempty"`

	// Principal Principal ARN making the request
	Principal string `json:"principal"`

	// Resource Resource ARN (e.g., arn:aws:rosa:us-west-2:123456789012:cluster/*)
	Resource string `json:"resource"`

	// ResourceTags Tags on the resource
	ResourceTags *map[string]string `json:"resourceTags,omitempty"`
}

// CheckAuthorizationResponse Authorization decision response
type CheckAuthorizationResponse struct {
	// Decision Authorization decision
	Decision CheckAuthorizationResponseDecision `json:"decision"`
	Kind     string                             `json:"kind"`

	// Reason Reason for the decision
	Reason *string `json:"reason,omitempty"`
}

// CheckAuthorizationResponseDecision Authorization decision
type CheckAuthorizationResponseDecision string

// Cluster A user cluster resource
type Cluster struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy Email of the user who created this cluster
	CreatedBy string `json:"created_by"`

	// Generation Generation number for optimistic concurrency control
	Generation int64 `json:"generation"`

	// Id Unique identifier for the cluster
	Id string `json:"id"`

	// Name Cluster name
	Name string `json:"name"`

	// ResourceVersion Resource version for optimistic concurrency control
	ResourceVersion string `json:"resource_version"`

	// Spec Cluster specification. When a cluster is created, the response includes
	// auto-populated fields like cloudUrl and placement.
	Spec Cluster_Spec `json:"spec"`

	// Status Kubernetes-like aggregated status for clusters
	Status *ClusterStatusInfo `json:"status,omitempty"`

	// TargetProjectId Target project ID
	TargetProjectId string `json:"target_project_id"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// Cluster_Spec Cluster specification. When a cluster is created, the response includes
// auto-populated fields like cloudUrl and placement.
type Cluster_Spec struct {
	// CloudUrl CloudFront URL with cluster ID appended (format: {cloudfront_url}/{cluster_id}).
	// This field is automatically added to the response when creating a cluster.
	CloudUrl *string `json:"cloudUrl,omitempty"`

	// Placement Management cluster name where the cluster is deployed.
	// Auto-populated from the first management cluster if not provided during creation.
	Placement            *string                `json:"placement,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ClusterControllerStatus Controller-specific status for a cluster
type ClusterControllerStatus struct {
	// ClusterId Cluster ID
	ClusterId *string `json:"cluster_id,omitempty"`

	// Conditions Controller-specific conditions
	Conditions *[]Condition `json:"conditions,omitempty"`

	// ControllerName Name of the controller
	ControllerName *string `json:"controller_name,omitempty"`

	// Data Controller-specific data
	Data *map[string]interface{} `json:"data,omitempty"`

	// LastUpdated When this controller last updated
	LastUpdated *time.Time `json:"last_updated,omitempty"`

	// Metadata Controller-specific metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// ObservedGeneration Last generation observed by this controller
	ObservedGeneration *int64 `json:"observed_generation,omitempty"`
}

// ClusterCreateRequest Request body for creating a cluster.
//
// The API automatically enriches the cluster spec with the following fields:
// - cloudUrl: Auto-populated from the first management cluster's cloudfront_url label
// - placement: Auto-populated from the first management cluster's name if not provided by the client
type ClusterCreateRequest struct {
	// Name DNS-compatible cluster name
	Name string `json:"name"`

	// Spec Cluster specification. The following fields are auto-populated if not provided:
	// - placement: Management cluster name where the cluster will be deployed (optional, auto-assigned if omitted)
	// - cloudUrl: CloudFront URL (always auto-populated from management cluster)
	Spec ClusterCreateRequest_Spec `json:"spec"`

	// TargetProjectId Target project ID
	TargetProjectId *string `json:"target_project_id,omitempty"`
}

// ClusterCreateRequest_Spec Cluster specification. The following fields are auto-populated if not provided:
// - placement: Management cluster name where the cluster will be deployed (optional, auto-assigned if omitted)
// - cloudUrl: CloudFront URL (always auto-populated from management cluster)
type ClusterCreateRequest_Spec struct {
	// Placement Management cluster name where the cluster will be deployed.
	// If not provided, will be auto-populated from the first available management cluster.
	Placement            *string                `json:"placement,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ClusterList Paginated list of clusters
type ClusterList struct {
	Items []Cluster `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// Total Total number of clusters
	Total int `json:"total"`
}

// ClusterStatusInfo Kubernetes-like aggregated status for clusters
type ClusterStatusInfo struct {
	// Conditions Status conditions
	Conditions *[]Condition `json:"conditions,omitempty"`

	// LastUpdateTime When status was last calculated
	LastUpdateTime *time.Time `json:"lastUpdateTime,omitempty"`

	// Message Human-readable status message
	Message *string `json:"message,omitempty"`

	// ObservedGeneration Last generation processed by controllers
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Phase High-level cluster phase
	Phase *ClusterStatusInfoPhase `json:"phase,omitempty"`

	// Reason Machine-readable reason code
	Reason *string `json:"reason,omitempty"`
}

// ClusterStatusInfoPhase High-level cluster phase
type ClusterStatusInfoPhase string

// ClusterStatusResponse Response for cluster status endpoint
type ClusterStatusResponse struct {
	// ClusterId Cluster ID
	ClusterId *string `json:"cluster_id,omitempty"`

	// ControllerStatuses Individual controller status reports
	ControllerStatuses *[]ClusterControllerStatus `json:"controller_statuses,omitempty"`

	// Status Kubernetes-like aggregated status for clusters
	Status *ClusterStatusInfo `json:"status,omitempty"`
}

// ClusterUpdateRequest Request body for updating a cluster
type ClusterUpdateRequest struct {
	// Spec Cluster specification
	Spec map[string]interface{} `json:"spec"`
}

// Condition Status condition
type Condition struct {
	// LastTransitionTime Last time the condition transitioned
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message Human-readable message
	Message *string `json:"message,omitempty"`

	// Reason Machine-readable reason code
	Reason *string `json:"reason,omitempty"`

	// Status Condition status
	Status *ConditionStatus `json:"status,omitempty"`

	// Type Condition type
	Type *string `json:"type,omitempty"`
}

// ConditionStatus Condition status
type ConditionStatus string

// CreateAttachmentRequest Request body for creating an attachment
type CreateAttachmentRequest struct {
	// PolicyId Policy ID to attach
	PolicyId openapi_types.UUID `json:"policyId"`

	// TargetId Target ID (ARN for user, groupId for group)
	TargetId string `json:"targetId"`

	// TargetType Type of target (user or group)
	TargetType CreateAttachmentRequestTargetType `json:"targetType"`
}

// CreateAttachmentRequestTargetType Type of target (user or group)
type CreateAttachmentRequestTargetType string

// CreateGroupRequest Request body for creating a group
type CreateGroupRequest struct {
	// Description Optional group description
	Description *string `json:"description,omitempty"`

	// Name Group name
	Name string `json:"name"`
}

// CreatePolicyRequest Request body for creating a policy
type CreatePolicyRequest struct {
	// Description Optional policy description
	Description *string `json:"description,omitempty"`

	// Name Policy name
	Name string `json:"name"`

	// Policy IAM-like policy in v0 format
	Policy V0Policy `json:"policy"`
}

// EnableAccountRequest Request body for enabling an account
type EnableAccountRequest struct {
	// AccountId AWS account ID to enable
	AccountId string `json:"accountId"`

	// Privileged If true, account bypasses all authorization checks
	Privileged *bool `json:"privileged,omitempty"`
}

// Error Error response
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Href API href reference
	Href *string `json:"href,omitempty"`

	// Id Error ID
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// OperationId Request operation ID for tracing
	OperationId *string `json:"operation_id,omitempty"`

	// Reason Human-readable error message
	Reason string `json:"reason"`
}

// Group A group of users
type Group struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Group description
	Description *string `json:"description,omitempty"`

	// Href API href reference
	Href string `json:"href"`

	// Id Group ID
	Id   openapi_types.UUID `json:"id"`
	Kind string             `json:"kind"`

	// MemberCount Number of members in the group
	MemberCount *int `json:"memberCount,omitempty"`

	// Name Group name
	Name string `json:"name"`
}

// GroupList Paginated list of groups
type GroupList struct {
	Items []Group `json:"items"`
	Kind  string  `json:"kind"`
	Page  int     `json:"page"`
	Size  int     `json:"size"`
	Total int     `json:"total"`
}

// GroupMember A member of a group
type GroupMember struct {
	// AddedAt When the member was added
	AddedAt time.Time `json:"addedAt"`

	// MemberArn Member's AWS ARN
	MemberArn string `json:"memberArn"`
}

// GroupMemberList Paginated list of group members
type GroupMemberList struct {
	Items []GroupMember `json:"items"`
	Kind  string        `json:"kind"`
	Page  int           `json:"page"`
	Size  int           `json:"size"`
	Total int           `json:"total"`
}

// HealthStatus Health check response
type HealthStatus struct {
	// Status Health status
	Status *HealthStatusStatus `json:"status,omitempty"`
}

// HealthStatusStatus Health status
type HealthStatusStatus string

// ManagementCluster A management cluster (passthrough from Maestro consumer)
type ManagementCluster struct {
	// CreatedAt Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Href API href reference
	Href string `json:"href"`

	// Id Unique identifier for the management cluster
	Id string `json:"id"`

	// Kind Resource kind
	Kind string `json:"kind"`

	// Labels Key-value labels
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Unique name of the management cluster
	Name string `json:"name"`

	// UpdatedAt Last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ManagementClusterList Paginated list of management clusters
type ManagementClusterList struct {
	Items []ManagementCluster `json:"items"`

	// Kind Resource kind
	Kind string `json:"kind"`

	// Page Current page number
	Page int `json:"page"`

	// Size Number of items per page
	Size int `json:"size"`

	// Total Total number of items
	Total int `json:"total"`
}

// ManagementClusterRequest Request body for creating a management cluster
type ManagementClusterRequest struct {
	// Labels Key-value labels for the management cluster
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Optional name for the management cluster.
	// Must follow RFC 1123 format (like Kubernetes namespace).
	// If not provided, defaults to the generated ID.
	Name *string `json:"name,omitempty"`
}

// NodePool A nodepool resource
type NodePool struct {
	// ClusterId Parent cluster ID
	ClusterId string `json:"cluster_id"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy Email of the user who created this nodepool
	CreatedBy string `json:"created_by"`

	// Generation Generation number for optimistic concurrency control
	Generation int64 `json:"generation"`

	// Id Unique identifier for the nodepool
	Id string `json:"id"`

	// Name NodePool name
	Name string `json:"name"`

	// ResourceVersion Resource version for optimistic concurrency control
	ResourceVersion string `json:"resource_version"`

	// Spec NodePool specification defining desired state
	Spec NodePoolSpec `json:"spec"`

	// Status Kubernetes-like aggregated status for nodepools
	Status *NodePoolStatusInfo `json:"status,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// NodePoolControllerStatus Controller-specific status for a nodepool
type NodePoolControllerStatus struct {
	// Conditions Controller-specific conditions
	Conditions *[]Condition `json:"conditions,omitempty"`

	// ControllerName Name of the controller
	ControllerName *string `json:"controller_name,omitempty"`

	// Data Controller-specific data
	Data *map[string]interface{} `json:"data,omitempty"`

	// LastUpdated When this controller last updated
	LastUpdated *time.Time `json:"last_updated,omitempty"`

	// Metadata Controller-specific metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// NodepoolId NodePool ID
	NodepoolId *string `json:"nodepool_id,omitempty"`

	// ObservedGeneration Last generation observed by this controller
	ObservedGeneration *int64 `json:"observed_generation,omitempty"`
}

// NodePoolCreateRequest Request body for creating a nodepool
type NodePoolCreateRequest struct {
	// ClusterId Parent cluster ID
	ClusterId string `json:"cluster_id"`

	// Name DNS-compatible nodepool name
	Name string `json:"name"`

	// Spec NodePool specification defining desired state
	Spec NodePoolSpec `json:"spec"`
}

// NodePoolList Paginated list of nodepools
type NodePoolList struct {
	Items []NodePool `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// Total Total number of nodepools
	Total int `json:"total"`
}

// NodePoolSpec NodePool specification defining desired state
type NodePoolSpec struct {
	// Management Node pool management configuration
	Management *map[string]interface{} `json:"management,omitempty"`

	// NodeDrainTimeout Timeout for draining nodes
	NodeDrainTimeout *string `json:"nodeDrainTimeout,omitempty"`

	// Platform Platform-specific configuration
	Platform *map[string]interface{} `json:"platform,omitempty"`

	// Release Release/version configuration
	Release *map[string]interface{} `json:"release,omitempty"`

	// Replicas Number of worker nodes in the pool
	Replicas *int32 `json:"replicas,omitempty"`
}

// NodePoolStatusInfo Kubernetes-like aggregated status for nodepools
type NodePoolStatusInfo struct {
	// Conditions Status conditions
	Conditions *[]Condition `json:"conditions,omitempty"`

	// LastUpdateTime When status was last calculated
	LastUpdateTime *time.Time `json:"lastUpdateTime,omitempty"`

	// Message Human-readable status message
	Message *string `json:"message,omitempty"`

	// ObservedGeneration Last generation processed by controllers
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Phase High-level nodepool phase
	Phase *NodePoolStatusInfoPhase `json:"phase,omitempty"`

	// Reason Machine-readable reason code
	Reason *string `json:"reason,omitempty"`
}

// NodePoolStatusInfoPhase High-level nodepool phase
type NodePoolStatusInfoPhase string

// NodePoolStatusResponse Response for nodepool status endpoint
type NodePoolStatusResponse struct {
	// ControllerStatuses Individual controller status reports
	ControllerStatuses *[]NodePoolControllerStatus `json:"controller_statuses,omitempty"`

	// NodepoolId NodePool ID
	NodepoolId *string `json:"nodepool_id,omitempty"`

	// Status Kubernetes-like aggregated status for nodepools
	Status *NodePoolStatusInfo `json:"status,omitempty"`
}

// NodePoolUpdateRequest Request body for updating a nodepool
type NodePoolUpdateRequest struct {
	// Spec NodePool specification defining desired state
	Spec NodePoolSpec `json:"spec"`
}

// Policy A policy template
type Policy struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Policy description
	Description *string `json:"description,omitempty"`

	// Href API href reference
	Href string `json:"href"`

	// Id Policy ID
	Id openapi_types.UUID `json:"id"`

	// Kind Resource kind
	Kind string `json:"kind"`

	// Name Policy name
	Name string `json:"name"`

	// Policy IAM-like policy in v0 format
	Policy V0Policy `json:"policy"`

	// UpdatedAt Last update timestamp
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// PolicyCondition Condition key-value pairs
type PolicyCondition map[string]PolicyCondition_AdditionalProperties

// PolicyCondition0 defines model for .
type PolicyCondition0 = string

// PolicyCondition1 defines model for .
type PolicyCondition1 = bool

// PolicyCondition2 defines model for .
type PolicyCondition2 = float32

// PolicyCondition3 defines model for .
type PolicyCondition3 = []string

// PolicyCondition_AdditionalProperties defines model for PolicyCondition.AdditionalProperties.
type PolicyCondition_AdditionalProperties struct {
	union json.RawMessage
}

// PolicyList Paginated list of policies
type PolicyList struct {
	Items []Policy `json:"items"`
	Kind  string   `json:"kind"`
	Page  int      `json:"page"`
	Size  int      `json:"size"`
	Total int      `json:"total"`
}

// PolicyStatement A single statement in a policy
type PolicyStatement struct {
	// Actions List of actions (e.g., rosa:CreateCluster)
	Actions []string `json:"actions"`

	// Conditions Optional conditions (operator -> key -> value)
	Conditions *map[string]PolicyCondition `json:"conditions,omitempty"`

	// Effect Allow or Deny
	Effect PolicyStatementEffect `json:"effect"`

	// Resources List of resources (* for all)
	Resources []string `json:"resources"`

	// Sid Optional statement ID
	Sid *string `json:"sid,omitempty"`
}

// PolicyStatementEffect Allow or Deny
type PolicyStatementEffect string

// ResourceBundle A resource bundle containing manifests for deployment
type ResourceBundle struct {
	// ConsumerName Name of the consumer this bundle is associated with
	ConsumerName *string `json:"consumer_name,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DeleteOption Deletion strategy for the resource bundle
	DeleteOption *map[string]interface{} `json:"delete_option,omitempty"`

	// DeletedAt Deletion timestamp (if soft-deleted)
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// Href API href reference
	Href string `json:"href"`

	// Id Unique identifier for the resource bundle
	Id string `json:"id"`

	// Kind Resource kind
	Kind string `json:"kind"`

	// ManifestConfigs Configuration for manifests
	ManifestConfigs *[]map[string]interface{} `json:"manifest_configs,omitempty"`

	// Manifests Array of Kubernetes manifests
	Manifests *[]map[string]interface{} `json:"manifests,omitempty"`

	// Metadata Additional metadata
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Name Name of the resource bundle
	Name string `json:"name"`

	// Status Status of the resource bundle
	Status *map[string]interface{} `json:"status,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Version Version number of the resource bundle
	Version *int `json:"version,omitempty"`
}

// ResourceBundleList Paginated list of resource bundles
type ResourceBundleList struct {
	Items []ResourceBundle `json:"items"`

	// Kind Resource kind
	Kind string `json:"kind"`

	// Page Current page number
	Page int `json:"page"`

	// Size Number of items per page
	Size int `json:"size"`

	// Total Total number of items
	Total int `json:"total"`
}

// UpdateGroupMembersRequest Request body for updating group members
type UpdateGroupMembersRequest struct {
	// Add ARNs to add to the group
	Add *[]string `json:"add,omitempty"`

	// Remove ARNs to remove from the group
	Remove *[]string `json:"remove,omitempty"`
}

// UpdatePolicyRequest Request body for updating a policy
type UpdatePolicyRequest struct {
	// Description Optional policy description
	Description *string `json:"description,omitempty"`

	// Name Policy name
	Name *string `json:"name,omitempty"`

	// Policy IAM-like policy in v0 format
	Policy *V0Policy `json:"policy,omitempty"`
}

// V0Policy IAM-like policy in v0 format
type V0Policy struct {
	// Statements List of policy statements
	Statements []PolicyStatement `json:"statements"`

	// Version Policy format version
	Version V0PolicyVersion `json:"version"`
}

// V0PolicyVersion Policy format version
type V0PolicyVersion string

// Work A manifestwork resource created for a cluster
type Work struct {
	// ClusterId Cluster ID this work is associated with
	ClusterId string `json:"cluster_id"`

	// CreatedAt Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Href API href reference
	Href string `json:"href"`

	// Id Unique identifier for the manifestwork
	Id string `json:"id"`

	// Kind Resource kind
	Kind string `json:"kind"`

	// Name Name of the manifestwork resource
	Name string `json:"name"`

	// Status Status of the manifestwork
	Status *map[string]interface{} `json:"status,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// WorkRequest Request body for creating manifestwork
type WorkRequest struct {
	// ClusterId Unique identifier of the target cluster
	ClusterId string `json:"cluster_id"`

	// Data Payload data to be passed to Maestro gRPC for creating the manifestwork.
	// This should contain the ManifestWork specification including manifests.
	Data map[string]interface{} `json:"data"`
}

// BadRequest Error response
type BadRequest = Error

// Conflict Error response
type Conflict = Error

// Forbidden Error response
type Forbidden = Error

// InternalError Error response
type InternalError = Error

// NotFound Error response
type NotFound = Error

// Unauthorized Error response
type Unauthorized = Error

// ListAdminsParams defines parameters for ListAdmins.
type ListAdminsParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// ListAttachmentsParams defines parameters for ListAttachments.
type ListAttachmentsParams struct {
	// PolicyId Filter by policy ID
	PolicyId *openapi_types.UUID `form:"policyId,omitempty" json:"policyId,omitempty"`

	// TargetType Filter by target type (user or group)
	TargetType *ListAttachmentsParamsTargetType `form:"targetType,omitempty" json:"targetType,omitempty"`

	// TargetId Filter by target ID (ARN for user, groupId for group)
	TargetId *string `form:"targetId,omitempty" json:"targetId,omitempty"`
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	Size     *int    `form:"size,omitempty" json:"size,omitempty"`
}

// ListAttachmentsParamsTargetType defines parameters for ListAttachments.
type ListAttachmentsParamsTargetType string

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// ListGroupMembersParams defines parameters for ListGroupMembers.
type ListGroupMembersParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// ListPoliciesParams defines parameters for ListPolicies.
type ListPoliciesParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// ListUserClustersParams defines parameters for ListUserClusters.
type ListUserClustersParams struct {
	// Limit Maximum number of clusters to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of clusters to skip (pagination)
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Status Filter by cluster status
	Status *ListUserClustersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListUserClustersParamsStatus defines parameters for ListUserClusters.
type ListUserClustersParamsStatus string

// DeleteUserClusterParams defines parameters for DeleteUserCluster.
type DeleteUserClusterParams struct {
	// Force Force delete even if cluster has active resources
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// ListManagementClustersParams defines parameters for ListManagementClusters.
type ListManagementClustersParams struct {
	// Page Page number (1-indexed)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Size Number of items per page
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// ListUserNodePoolsParams defines parameters for ListUserNodePools.
type ListUserNodePoolsParams struct {
	// ClusterId Filter by cluster ID (optional)
	ClusterId *string `form:"clusterId,omitempty" json:"clusterId,omitempty"`

	// Limit Maximum number of nodepools to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of nodepools to skip (pagination)
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListResourceBundlesParams defines parameters for ListResourceBundles.
type ListResourceBundlesParams struct {
	// Page Page number (1-indexed)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Size Number of items per page
	Size *int `form:"size,omitempty" json:"size,omitempty"`

	// Search SQL-like filter criteria on resource attributes
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// OrderBy SQL-like ordering (e.g., "name asc")
	OrderBy *string `form:"orderBy,omitempty" json:"orderBy,omitempty"`

	// Fields Comma-separated list of fields to return
	Fields *string `form:"fields,omitempty" json:"fields,omitempty"`

	// XOperationID Optional operation ID for tracking
	XOperationID *string `json:"X-Operation-ID,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = EnableAccountRequest

// AddAdminJSONRequestBody defines body for AddAdmin for application/json ContentType.
type AddAdminJSONRequestBody = AddAdminRequest

// CreateAttachmentJSONRequestBody defines body for CreateAttachment for application/json ContentType.
type CreateAttachmentJSONRequestBody = CreateAttachmentRequest

// CheckAuthorizationJSONRequestBody defines body for CheckAuthorization for application/json ContentType.
type CheckAuthorizationJSONRequestBody = CheckAuthorizationRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupMembersJSONRequestBody defines body for UpdateGroupMembers for application/json ContentType.
type UpdateGroupMembersJSONRequestBody = UpdateGroupMembersRequest

// CreatePolicyJSONRequestBody defines body for CreatePolicy for application/json ContentType.
type CreatePolicyJSONRequestBody = CreatePolicyRequest

// UpdatePolicyJSONRequestBody defines body for UpdatePolicy for application/json ContentType.
type UpdatePolicyJSONRequestBody = UpdatePolicyRequest

// CreateUserClusterJSONRequestBody defines body for CreateUserCluster for application/json ContentType.
type CreateUserClusterJSONRequestBody = ClusterCreateRequest

// PatchUserClusterJSONRequestBody defines body for PatchUserCluster for application/json ContentType.
type PatchUserClusterJSONRequestBody = ClusterUpdateRequest

// UpdateUserClusterJSONRequestBody defines body for UpdateUserCluster for application/json ContentType.
type UpdateUserClusterJSONRequestBody = ClusterUpdateRequest

// CreateManagementClusterJSONRequestBody defines body for CreateManagementCluster for application/json ContentType.
type CreateManagementClusterJSONRequestBody = ManagementClusterRequest

// CreateUserNodePoolJSONRequestBody defines body for CreateUserNodePool for application/json ContentType.
type CreateUserNodePoolJSONRequestBody = NodePoolCreateRequest

// UpdateUserNodePoolJSONRequestBody defines body for UpdateUserNodePool for application/json ContentType.
type UpdateUserNodePoolJSONRequestBody = NodePoolUpdateRequest

// CreateWorkJSONRequestBody defines body for CreateWork for application/json ContentType.
type CreateWorkJSONRequestBody = WorkRequest

// Getter for additional properties for Cluster_Spec. Returns the specified
// element and whether it was found
func (a Cluster_Spec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Cluster_Spec
func (a *Cluster_Spec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Cluster_Spec to handle AdditionalProperties
func (a *Cluster_Spec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cloudUrl"]; found {
		err = json.Unmarshal(raw, &a.CloudUrl)
		if err != nil {
			return fmt.Errorf("error reading 'cloudUrl': %w", err)
		}
		delete(object, "cloudUrl")
	}

	if raw, found := object["placement"]; found {
		err = json.Unmarshal(raw, &a.Placement)
		if err != nil {
			return fmt.Errorf("error reading 'placement': %w", err)
		}
		delete(object, "placement")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Cluster_Spec to handle AdditionalProperties
func (a Cluster_Spec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CloudUrl != nil {
		object["cloudUrl"], err = json.Marshal(a.CloudUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cloudUrl': %w", err)
		}
	}

	if a.Placement != nil {
		object["placement"], err = json.Marshal(a.Placement)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'placement': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ClusterCreateRequest_Spec. Returns the specified
// element and whether it was found
func (a ClusterCreateRequest_Spec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ClusterCreateRequest_Spec
func (a *ClusterCreateRequest_Spec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClusterCreateRequest_Spec to handle AdditionalProperties
func (a *ClusterCreateRequest_Spec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["placement"]; found {
		err = json.Unmarshal(raw, &a.Placement)
		if err != nil {
			return fmt.Errorf("error reading 'placement': %w", err)
		}
		delete(object, "placement")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClusterCreateRequest_Spec to handle AdditionalProperties
func (a ClusterCreateRequest_Spec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Placement != nil {
		object["placement"], err = json.Marshal(a.Placement)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'placement': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsPolicyCondition0 returns the union data inside the PolicyCondition_AdditionalProperties as a PolicyCondition0
func (t PolicyCondition_AdditionalProperties) AsPolicyCondition0() (PolicyCondition0, error) {
	var body PolicyCondition0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyCondition0 overwrites any union data inside the PolicyCondition_AdditionalProperties as the provided PolicyCondition0
func (t *PolicyCondition_AdditionalProperties) FromPolicyCondition0(v PolicyCondition0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyCondition0 performs a merge with any union data inside the PolicyCondition_AdditionalProperties, using the provided PolicyCondition0
func (t *PolicyCondition_AdditionalProperties) MergePolicyCondition0(v PolicyCondition0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolicyCondition1 returns the union data inside the PolicyCondition_AdditionalProperties as a PolicyCondition1
func (t PolicyCondition_AdditionalProperties) AsPolicyCondition1() (PolicyCondition1, error) {
	var body PolicyCondition1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyCondition1 overwrites any union data inside the PolicyCondition_AdditionalProperties as the provided PolicyCondition1
func (t *PolicyCondition_AdditionalProperties) FromPolicyCondition1(v PolicyCondition1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyCondition1 performs a merge with any union data inside the PolicyCondition_AdditionalProperties, using the provided PolicyCondition1
func (t *PolicyCondition_AdditionalProperties) MergePolicyCondition1(v PolicyCondition1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolicyCondition2 returns the union data inside the PolicyCondition_AdditionalProperties as a PolicyCondition2
func (t PolicyCondition_AdditionalProperties) AsPolicyCondition2() (PolicyCondition2, error) {
	var body PolicyCondition2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyCondition2 overwrites any union data inside the PolicyCondition_AdditionalProperties as the provided PolicyCondition2
func (t *PolicyCondition_AdditionalProperties) FromPolicyCondition2(v PolicyCondition2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyCondition2 performs a merge with any union data inside the PolicyCondition_AdditionalProperties, using the provided PolicyCondition2
func (t *PolicyCondition_AdditionalProperties) MergePolicyCondition2(v PolicyCondition2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolicyCondition3 returns the union data inside the PolicyCondition_AdditionalProperties as a PolicyCondition3
func (t PolicyCondition_AdditionalProperties) AsPolicyCondition3() (PolicyCondition3, error) {
	var body PolicyCondition3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyCondition3 overwrites any union data inside the PolicyCondition_AdditionalProperties as the provided PolicyCondition3
func (t *PolicyCondition_AdditionalProperties) FromPolicyCondition3(v PolicyCondition3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyCondition3 performs a merge with any union data inside the PolicyCondition_AdditionalProperties, using the provided PolicyCondition3
func (t *PolicyCondition_AdditionalProperties) MergePolicyCondition3(v PolicyCondition3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PolicyCondition_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PolicyCondition_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
