// Code generated by conversion-gen. DO NOT EDIT.

package public

// APIServerNetworkConfiguration is the REST representation of APIServerNetworkConfiguration (visible fields only)
type APIServerNetworkConfiguration struct {
}
