// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// ClusterNetworking specifies network configuration for the cluster.
// +hyperfleet:upstream-reduced-object=hypershiftv1beta1.ClusterNetworking
type ClusterNetworking struct {
	// machineNetwork is the list of IP address pools for machines.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:MaxItems=2
	// +kubebuilder:validation:MinItems=1
	MachineNetwork []MachineNetworkEntry `json:"machineNetwork,omitempty"`
	// clusterNetwork is the list of IP address pools for pods.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:MaxItems=2
	// +kubebuilder:validation:MinItems=1
	ClusterNetwork []ClusterNetworkEntry `json:"clusterNetwork,omitempty"`
	// serviceNetwork is the list of IP address pools for services.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:MaxItems=2
	// +kubebuilder:validation:MinItems=1
	ServiceNetwork []ServiceNetworkEntry `json:"serviceNetwork,omitempty"`
	// networkType specifies the SDN provider used for cluster networking.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=immutable
	NetworkType hypershiftv1beta1.NetworkType `json:"networkType,omitempty"`
}
