// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	configv1 "github.com/openshift/api/config/v1"
)

// ClusterAuthentication contains the customer-configurable authentication settings.
// +kubebuilder:validation:XValidation:rule="!has(self.oidcProviders) || size(self.oidcProviders) == 0 || self.type == 'OIDC'",message="type must be OIDC when oidcProviders are configured"
type ClusterAuthentication struct {
	// type identifies the authentication mode. Set it to OIDC when configuring oidcProviders.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=mutable
	// +optional
	Type string `json:"type,omitempty"`
	// oidcProviders are OIDC identity providers that can issue tokens for this cluster.
	// At most one provider can be configured. Set type to OIDC to enable these providers.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=mutable
	// +listType=map
	// +listMapKey=name
	// +kubebuilder:validation:MaxItems=1
	// +optional
	OIDCProviders []configv1.OIDCProvider `json:"oidcProviders,omitempty"`
}
