// Code generated by conversion-gen. DO NOT EDIT.

package public

// ClusterConfiguration specifies configuration for individual OCP components in the cluster.
// This is a HyperFleet-owned mirror of hypershiftv1beta1.ClusterConfiguration that allows
// us to add granular markers to nested fields like kubelet config.
// +hyperfleet:upstream-reduced-object=hypershiftv1beta1.ClusterConfiguration
type ClusterConfiguration struct {
	// network contains the configuration for cluster networking.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=service-set
	Network *NetworkConfiguration `json:"network,omitempty"`
	// kubelet contains the configuration for kubelet on nodes.
	// +hyperfleet:write-mode=service-set
	Kubelet *KubeletConfig `json:"kubelet,omitempty"`
	// machineConfig contains the configuration for machine-level settings.
	// +hyperfleet:write-mode=service-set
	MachineConfig *MachineConfigSpec `json:"machineConfig,omitempty"`
}
