// Code generated by conversion-gen. DO NOT EDIT.

package public

// ClusterNetworkEntry is a contiguous block of IP addresses for pods.
type ClusterNetworkEntry struct {
	// cidr is the complete block for pod IPs.
	// +hyperfleet:write-mode=immutable
	CIDR string `json:"cidr"`
	// hostPrefix is the size (prefix) of block to allocate to each node.
	// +hyperfleet:write-mode=immutable
	HostPrefix uint32 `json:"hostPrefix,omitempty"`
}
