// Code generated by conversion-gen. DO NOT EDIT.

package public

// MachineNetworkEntry is a single IP address block for node IPs.
// +hyperfleet:upstream-reduced-object=hypershiftv1beta1.MachineNetworkEntry
type MachineNetworkEntry struct {
	// cidr is the IP block address pool for machines.
	// +hyperfleet:write-mode=immutable
	CIDR string `json:"cidr"`
}
