// Code generated by conversion-gen. DO NOT EDIT.
// MANUAL WORKAROUND: This file is manually maintained. See .manual-types-readme.md

package public

// NetworkConfiguration specifies cluster network configuration.
type NetworkConfiguration struct {
	// clusterNetwork is the IP address pool to use for pod IPs.
	// +hyperfleet:write-mode=immutable
	ClusterNetwork []ClusterNetworkEntry `json:"clusterNetwork,omitempty"`
	// serviceNetwork is the IP address pool for services.
	// +hyperfleet:write-mode=immutable
	ServiceNetwork []string `json:"serviceNetwork,omitempty"`
	// networkType is the plugin to be deployed (e.g. OVNKubernetes).
	// +hyperfleet:write-mode=immutable
	NetworkType string `json:"networkType,omitempty"`
	// serviceNodePortRange is the port range for Services of type NodePort.
	// +hyperfleet:write-mode=mutable
	ServiceNodePortRange string `json:"serviceNodePortRange,omitempty"`
}
