// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
)

// NetworkConfiguration specifies cluster network configuration.
// +hyperfleet:upstream-reduced-object=configv1.NetworkSpec
type NetworkConfiguration struct {
	// clusterNetwork is the IP address pool to use for pod IPs.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:MaxItems=32
	ClusterNetwork []v1alpha1.ClusterNetworkEntry `json:"clusterNetwork,omitempty"`
	// serviceNetwork is the IP address pool for services.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:MaxItems=32
	ServiceNetwork []string `json:"serviceNetwork,omitempty"`
	// networkType is the plugin to be deployed (e.g. OVNKubernetes).
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=immutable
	NetworkType string `json:"networkType,omitempty"`
	// serviceNodePortRange is the port range for Services of type NodePort.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=mutable
	ServiceNodePortRange string `json:"serviceNodePortRange,omitempty"`
}
