// Code generated by conversion-gen. DO NOT EDIT.

package public

// ServiceNetworkEntry is a single IP address block for service IPs.
// +hyperfleet:upstream-reduced-object=hypershiftv1beta1.ServiceNetworkEntry
type ServiceNetworkEntry struct {
	// cidr is the IP block address pool for services.
	// +hyperfleet:write-mode=immutable
	CIDR string `json:"cidr"`
}
